# Generated by Django 5.1.2 on 2024-11-05 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wft', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characterorbuild',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='locate',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='maps',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='starterskill',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='upgrade',
            name='slug',
        ),
    ]
