# Generated by Django 5.1.2 on 2024-11-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wft', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterorbuild',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='characterorbuild',
            name='type_unit',
            field=models.ManyToManyField(blank=True, related_name='char', to='wft.targets'),
        ),
    ]
